- css/style.css
> update css style like twitter

- css/style.css
調子にのって名前周りの表示をQiitadonっぽくしてみました。 ~~idがユーザーページへのリンクになるとよりそれっぽくなりそうです~~
また、バルーン表示ではなくボーダーのも(雑に)書いてみたのでいい感じな方を使ってください。
> update style like Qiitadon

- css/style.css
- js/index.js
- js/p.js
issue: https://github.com/hidao80/mastogetter/issues/6
toot した時間を 追加する。
created_at は存在するものとして扱ってしまってます。
css はdisplay-nameとは別に変更したくなるかもしれないので class分けしてます。
> toot した時間を 追加する。

- css/style.css
> fix wordbreak and img size in mobile view

- css/style.css
デサイン開発ブランチで対応した fix wordbreak and img size in mobile view #12 をマージします。
> モバイルデバイス画面対応 #8

- index.html
- js/index.js
#13 「追加」ボタンのラベルが分かりづらい
#14 シングルクリックで項目削除は操作ミスが多い
を解決しました。
> #13, #14 の解決

- css/style.css
- index.html
#4 と #23 に関連した修正です。 tootの表示のなかで`a`タグが崩れる問題を修正しました。
> fix display collapses in toot card

- css/style.css
- index.html
環境によって2ペインにならない事があるので、width>899pxの環境での.areaクラスのwidthを44.5%に変更
> fix .area width

- index.html
- p.html
#31 
#32 で誤った URL を指定していたので修正しました。
> ページヘッダの URL の訂正

- css/reset.css
- css/style.css
- index.html
- js/common.js
- js/index.js
- p.html
タブ・インデントとスペース・インデントが混在していたので統一しました。
> インデントの混在をタブに統一

- css/style.css
- index.html
cssで推奨されない書き方をしていたり、不自然な書き方になっていたところを直しました
> 🧹: refactoring css + html

- js/common.js
- js/index.js
see: https://github.com/hidao80/mastogetter/issues/10
drag drop すると drop した toot の `上` に移動するようにしてみた。
ただ、どのブラウザまで動くのかはよくわかりません。
> add: support drag-drop

- css/style.css
> fix: balloon came back

- css/style.css
- index.html
- js/common.js
- js/index.js
- feat: https://github.com/hidao80/mastogetter/issues/33
- fix https://github.com/hidao80/mastogetter/issues/41
<kbd><img width="100%" alt="スクリーンショット 2020-01-08 16 59 15" src="https://user-images.githubusercontent.com/11840938/71960384-3d867200-3238-11ea-82b7-3deaf5570c42.png"></kbd>
<kbd><img width="100%" alt="スクリーンショット 2020-01-08 17 02 33" src="https://user-images.githubusercontent.com/11840938/71960634-d4532e80-3238-11ea-962e-d1c97dfaa831.png"></kbd>
こんな感じになりました。
> feat: #33 短縮 URL 作成（チェックボックス・タイプ）作成

- css/style.css
- js/common.js
- js/index.js
resolved #19 
- アイコン、ユーザー名をクリックするとユーザページを新しいタブで開くように
- ついでにタイムスタンプをクリックすると元tootを新しいタブで開くように
> Resolve: ユーザ名をクリックしたらユーザページへ飛んでほしい #19

- js/common.js
- js/index.js
- var、let、constが混同していたので、varを削除してletとconstに統一しました
- 衝突していた変数名を変更しました
- 汎用的な意味を持つ変数名を変更しました
- 複雑なロジックのコードを簡潔にしました
> jsのリファクタリングと可読性向上

- js/index.js
> fix: ユーザー名に含まれるインスタンス名を正しく表示する

- js/index.js
resolve #76 
編集ページにある入力欄4つすべてに、
focus 時に全選択するようにしてみました。
> Resolve: URL 欄をクリックしたら選択状態にして欲しい #76

- js/common.js
- js/index.js
> fix: make relative

- js/common.js
- js/index.js
まずは、自前で指定しているアンカーのみの修正で Draft PR します。
アンカーに `target="_blank" rel="noopener nofollow"` を付けるのは関数化したいので、チャレンジしてみます。
できたら Draft を外すので、その際はレビューをお願いします。
---
- ~~a8c2383 で関数化したが CI が通らない~~ → d33bb7a で CI パス。
> fix: #91 Tabnabbing 脆弱性の修正

- css/style.css
- index.html
- p.html
> fix: flipボタンのスタイルを修正

- js/index.js
eventListener の設定漏れ
refs #85
https://github.com/Qithub-BOT/mastogetter/blob/6b2d136d69fd599316fe900b40749be5c914caa6/js/common.js#L177-L179
> fix: 編集画面で並び替え・削除ができない

- css/style.css
- js/common.js
- js/index.js
> Resolve: Emoji 対応 #103

- .eslintrc.json
- css/style.css
- index.html
- js/index.js
introJSというものを追加しています。使い方ボタンを押すと、添付画像のような表示になります。
html主体とJS主体とで少し書き方が違うのですが、今回は悩んだ結果htmlに書いています。
コメントなどは適宜修正の上ご利用ください。~~使い方の説明は要らない説もありますが~~
> feat: introJSの追加

- js/common.js
- js/index.js
- js/p.js
for #118 
fetchのエラー処理は共通化するほうが読みやすくなると考えたので`fetchJsonAndCheck`を作った
また合わせて見つけた過去の消し忘れた処理たちを消した
> fetchJsonAndCheckの導入など
